'use strict';

/**
 * Frozen roster construction: the 50 rosters per season-week the regret
 * estimands are measured over.
 *
 * Every number here is preregistered (section 5.1) and none of it may depend on
 * a model. That independence is the point: if the rosters were built from any
 * arm's projections, the arm would be graded on a board it drew itself, and the
 * regret comparison would be circular. So the ranking is a pure
 * recency-weighted mean of PRIOR league-scored points re-scored from the pinned
 * raw stats, the draft is a deterministic snake, and the seed is fixed.
 *
 * THE SLOT-COUNT GUARD. The number of starting slots is the SUM of
 * `slot.count`, which is 9. It is NOT `rosterSlots.length`, which is 7, because
 * RB and WR each carry `count: 2`. The legacy harness this study replaces had
 * exactly that bug - it graded nine-slot lineups as though they had seven - and
 * it is one of the four defects that invalidated `free_baseline_v3.1`'s
 * constants. A mutant that swaps the sum for `.length` must fail a test, and
 * one does.
 *
 * Artifacts are GENERATED by this module after the preregistration sealed
 * (their construction rules are in it) and committed in freeze Commit A. The
 * sweep LOADS them; it never regenerates them. That is why the freeze hash
 * below exists.
 *
 * Pure: no database, no filesystem, no clock, no `Math.random`.
 */

const crypto = require('crypto');

const { canonicalJson } = require('./snapshotStore');

/** Preregistration 5.1, exactly. */
const ROSTER_SEED = 1357931762;
const CANDIDATE_QUOTAS = Object.freeze({ QB: 20, RB: 50, WR: 50, TE: 20, K: 10, DEF: 10 });
const POOL_SIZE = 160;
const TEAM_COUNT = 10;
const ROUNDS = 16;
const REPLICATES = 5;
const PER_TEAM_CAPS = Object.freeze({ QB: 2, RB: 5, WR: 5, TE: 2, K: 1, DEF: 1 });
const BENCH_SLOTS = 7;
const IR_SLOTS = 0;
const RECENCY_HALF_LIFE_WEEKS = 8;
const HISTORY_SEASONS = 2;

/** The app's `DEFAULT_ROSTER_SLOTS` (lineup.service.js:26), mirrored. */
const DEFAULT_ROSTER_SLOTS = Object.freeze([
  Object.freeze({ key: 'QB', count: 1, eligiblePositions: Object.freeze(['QB']) }),
  Object.freeze({ key: 'RB', count: 2, eligiblePositions: Object.freeze(['RB']) }),
  Object.freeze({ key: 'WR', count: 2, eligiblePositions: Object.freeze(['WR']) }),
  Object.freeze({ key: 'TE', count: 1, eligiblePositions: Object.freeze(['TE']) }),
  Object.freeze({ key: 'FLEX', count: 1, eligiblePositions: Object.freeze(['RB', 'WR', 'TE']) }),
  Object.freeze({ key: 'K', count: 1, eligiblePositions: Object.freeze(['K']) }),
  Object.freeze({ key: 'DEF', count: 1, eligiblePositions: Object.freeze(['DEF']) }),
]);

/**
 * The fixed fill order for the initial lineup (prereg 5.1). Nine entries,
 * because RB and WR are filled twice - which is the same fact the slot-count
 * guard protects, written out.
 */
const INITIAL_FILL_ORDER = Object.freeze(['QB', 'RB', 'RB', 'WR', 'WR', 'TE', 'FLEX', 'K', 'DEF']);

/**
 * THE GUARD. Sum of `count`, never `.length`.
 *
 * Written as its own exported function so the mutation test has one line to
 * attack and every caller gets the right answer by construction.
 */
function startingSlotCount(rosterSlots = DEFAULT_ROSTER_SLOTS) {
  return rosterSlots.reduce((total, slot) => total + Number(slot.count), 0);
}

/** Roster size = starters + bench. 9 + 7 = 16, and 16 x 10 teams = the pool. */
function rosterSize(rosterSlots = DEFAULT_ROSTER_SLOTS, benchSlots = BENCH_SLOTS) {
  return startingSlotCount(rosterSlots) + benchSlots;
}

// ---------------------------------------------------------------------------
// Deterministic seeding
// ---------------------------------------------------------------------------

/**
 * Pure: a stable 32-bit seed from the roster seed and a tuple.
 *
 * SHA-256 of a canonical string rather than a hand-rolled hash: the artifacts
 * are committed and must regenerate byte-identically on another machine and
 * another Node version, and a bit-mixing function written here would be one
 * more thing to get subtly wrong.
 */
function seedFor(...parts) {
  const digest = crypto.createHash('sha256')
    .update(`${ROSTER_SEED}|${parts.join('|')}`, 'utf8')
    .digest();
  return digest.readUInt32BE(0);
}

/** Pure: a deterministic 32-bit PRNG (mulberry32), so no global RNG is touched. */
function makeRng(seed) {
  let a = seed >>> 0;
  return function next() {
    a = (a + 0x6d2b79f5) >>> 0;
    let t = a;
    t = Math.imul(t ^ (t >>> 15), t | 1);
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

/** Pure: a seeded Fisher-Yates permutation. Never mutates the input. */
function seededPermutation(items, seed) {
  const out = [...items];
  const rng = makeRng(seed);
  for (let i = out.length - 1; i > 0; i--) {
    const j = Math.floor(rng() * (i + 1));
    [out[i], out[j]] = [out[j], out[i]];
  }
  return out;
}

// ---------------------------------------------------------------------------
// The model-independent ranking
// ---------------------------------------------------------------------------

/**
 * Pure: how many "recency weeks" separate a prior game from the target week.
 * Mirrors `projectionFeatures.weeksAgo` with the model's season span, so a
 * prior-season game decays the way the engine would decay it.
 */
function weeksAgo({ gameSeason, gameWeek, season, week, seasonWeekSpan = 18 }) {
  return (Number(season) - Number(gameSeason)) * seasonWeekSpan + (Number(week) - Number(gameWeek));
}

/**
 * Pure: the preregistered pre-week ranking score for one player.
 *
 * Recency-weighted mean of prior league-scored points, weight
 * `0.5^(weeksAgo/8)`, two-season window, at least one prior game. Identical in
 * form to the `naive-recency` benchmark - deliberately, because both are "what
 * you would guess from his recent scoring alone", and using the same rule for
 * the draft board keeps the board free of any arm's opinion.
 *
 * Returns `null` for a player with no prior game: he is not rankable, and the
 * caller excludes him rather than inventing a zero that would sort him last but
 * still on the board.
 */
function recencyWeightedScore({
  priorGames, season, week, halfLifeWeeks = RECENCY_HALF_LIFE_WEEKS,
  historySeasons = HISTORY_SEASONS, seasonWeekSpan = 18,
}) {
  const firstSeason = Number(season) - historySeasons;
  let weighted = 0;
  let weight = 0;
  let games = 0;
  for (const game of priorGames || []) {
    const gameSeason = Number(game.season);
    const gameWeek = Number(game.week);
    // Two-season window, and strictly BEFORE the target week.
    if (gameSeason < firstSeason) continue;
    if (gameSeason > Number(season)) continue;
    if (gameSeason === Number(season) && gameWeek >= Number(week)) continue;
    const points = Number(game.points);
    if (!Number.isFinite(points)) continue;
    const ago = weeksAgo({ gameSeason, gameWeek, season, week, seasonWeekSpan });
    const w = Math.pow(0.5, ago / halfLifeWeeks);
    weighted += w * points;
    weight += w;
    games++;
  }
  if (games < 1 || weight <= 0) return null;
  return { score: weighted / weight, games };
}

/**
 * Pure: rank candidates, breaking ties by `(position rank, name rank, id)`.
 *
 * The tiebreak artifacts are the DB-produced collation ranks captured in Phase
 * 1 - PostgreSQL's own ordering, never a JS comparator and never
 * `Intl.Collator`. **Fail closed if an evaluated player lacks a rank**: an
 * unranked player would sort arbitrarily, and the whole point of capturing the
 * artifacts was to remove arbitrariness from candidate order.
 */
function rankCandidates({ candidates, positionRank, nameRankById, label = 'ranking' }) {
  const ranked = candidates.map((candidate) => {
    const posRank = positionRank.get(candidate.position);
    if (posRank === undefined) {
      throw new Error(
        `${label}: position ${JSON.stringify(candidate.position)} has no captured rank. The ` +
        'position-code ordering is a DB collation artifact and every evaluated position must be in it.'
      );
    }
    // A DEF pseudo-player has no database id and therefore no name rank; it is
    // ranked by its team key instead, which is unique per team-week.
    const nameRank = candidate.isDefense
      ? null
      : nameRankById.get(Number(candidate.playerId));
    if (!candidate.isDefense && nameRank === undefined) {
      throw new Error(
        `${label}: player ${candidate.playerId} has no captured name rank, so candidate order would ` +
        'be arbitrary. The deployed-policy wrapper fails closed here for the same reason.'
      );
    }
    return { ...candidate, positionRank: posRank, nameRank };
  });

  ranked.sort((a, b) => {
    // Score first, descending: this IS the board.
    if (b.score !== a.score) return b.score - a.score;
    if (a.positionRank !== b.positionRank) return a.positionRank - b.positionRank;
    const an = a.nameRank === null ? Number.MAX_SAFE_INTEGER : a.nameRank;
    const bn = b.nameRank === null ? Number.MAX_SAFE_INTEGER : b.nameRank;
    if (an !== bn) return an - bn;
    const aid = String(a.playerId ?? a.teamKey);
    const bid = String(b.playerId ?? b.teamKey);
    return aid < bid ? -1 : aid > bid ? 1 : 0;
  });
  return ranked;
}

/**
 * Pure: take the preregistered quota from each position, in rank order.
 *
 * Fail closed on a short position: the caps below exactly exhaust a full pool,
 * so a pool of 158 would silently produce illegal rosters at the end of the
 * draft rather than an error.
 */
function selectCandidatePool({ ranked, quotas = CANDIDATE_QUOTAS, label = 'pool' }) {
  const pool = [];
  const shortfalls = {};
  for (const [position, quota] of Object.entries(quotas)) {
    const atPosition = ranked.filter((c) => c.position === position);
    if (atPosition.length < quota) shortfalls[position] = atPosition.length;
    pool.push(...atPosition.slice(0, quota));
  }
  if (Object.keys(shortfalls).length > 0) {
    throw new Error(
      `${label}: the candidate pool is short at ${Object.entries(shortfalls)
        .map(([p, n]) => `${p} (${n} of ${quotas[p]})`).join(', ')}. The per-team caps exactly ` +
      'exhaust a full pool, so a short one would produce illegal rosters instead of an error.'
    );
  }
  const expected = Object.values(quotas).reduce((a, b) => a + b, 0);
  if (pool.length !== expected) {
    throw new Error(`${label}: built ${pool.length} candidates, expected ${expected}`);
  }
  // Return the pool in GLOBAL rank order, not grouped by position.
  //
  // The quotas are applied per position, so the loop above necessarily builds
  // the pool position by position - but the draft's rule is "each pick takes
  // the HIGHEST-RANKED remaining player the caps still allow" (prereg 5.1), and
  // `snakeDraft` reads that as the first eligible entry in this array. Leaving
  // it position-grouped would silently mean "the highest-ranked remaining
  // player within the first position group that still has room", which is a
  // different draft and a different board.
  const rankOf = new Map(ranked.map((candidate, index) => [candidate, index]));
  return pool.sort((a, b) => rankOf.get(a) - rankOf.get(b));
}

// ---------------------------------------------------------------------------
// The draft
// ---------------------------------------------------------------------------

/**
 * Pure: a snake draft into 10 legal 16-man rosters.
 *
 * Each pick takes the highest-ranked remaining player the per-team caps still
 * allow (prereg 5.1). The caps exactly exhaust the pool, so every roster is
 * legal by construction rather than by repair - there is no "fix up the roster
 * afterwards" step that could introduce a model-dependent choice.
 */
function snakeDraft({
  pool, season, week, replicate, teamCount = TEAM_COUNT, rounds = ROUNDS,
  caps = PER_TEAM_CAPS, label = 'draft',
}) {
  if (pool.length !== teamCount * rounds) {
    throw new Error(`${label}: pool of ${pool.length} cannot fill ${teamCount} x ${rounds} rosters`);
  }
  // "Each pick takes the highest-ranked remaining player the caps allow" is
  // read below as "the first eligible entry in this array", so the array MUST
  // already be in rank order. Asserted rather than re-sorted: a defensive sort
  // here would duplicate `rankCandidates`'s comparator, and two copies of a
  // tie-break rule are two things to keep in step. The assert catches the
  // realistic faults - a pool still grouped by position, or one shuffled by a
  // caller - without owning the ordering.
  for (let i = 1; i < pool.length; i++) {
    if (pool[i - 1].score < pool[i].score) {
      throw new Error(
        `${label}: the candidate pool is not in rank order at index ${i} ` +
        `(${pool[i - 1].score} then ${pool[i].score}). The draft reads array order as rank, so a ` +
        'pool grouped by position would silently mean "the best player in the first position ' +
        'group with room" - a different board.'
      );
    }
  }
  // The replicate's draft ORDER is the seeded permutation of the team slots.
  const order = seededPermutation(
    Array.from({ length: teamCount }, (unused, i) => i),
    seedFor('draft-order', season, week, replicate)
  );
  const teams = Array.from({ length: teamCount }, (unused, i) => ({
    teamIndex: i,
    draftSlot: order.indexOf(i),
    picks: [],
    byPosition: {},
  }));
  const available = [...pool];

  for (let round = 0; round < rounds; round++) {
    // Snake: odd rounds reverse.
    const roundOrder = round % 2 === 0 ? order : [...order].reverse();
    for (const teamIndex of roundOrder) {
      const team = teams[teamIndex];
      const pickIndex = available.findIndex((candidate) => {
        const taken = team.byPosition[candidate.position] || 0;
        return taken < caps[candidate.position];
      });
      if (pickIndex < 0) {
        throw new Error(
          `${label}: team ${teamIndex} has no legal pick in round ${round + 1}; the caps and the ` +
          'pool quotas are supposed to make that impossible'
        );
      }
      const [picked] = available.splice(pickIndex, 1);
      team.picks.push(picked);
      team.byPosition[picked.position] = (team.byPosition[picked.position] || 0) + 1;
    }
  }
  if (available.length !== 0) {
    throw new Error(`${label}: ${available.length} candidates left undrafted`);
  }
  for (const team of teams) {
    for (const [position, cap] of Object.entries(caps)) {
      const taken = team.byPosition[position] || 0;
      if (taken !== cap) {
        throw new Error(
          `${label}: team ${team.teamIndex} holds ${taken} ${position}, the cap is ${cap}; ` +
          'the caps must exactly exhaust the pool or a roster is not legal by construction'
        );
      }
    }
  }
  return teams;
}

// ---------------------------------------------------------------------------
// The initial lineup
// ---------------------------------------------------------------------------

/**
 * Pure: the seeded, model-independent starter/bench state each roster begins
 * with (prereg 5.1).
 *
 * Fill the nine starting slots in the fixed order QB, RB, RB, WR, WR, TE, FLEX,
 * K, DEF, each with the highest-ranked eligible unassigned player under the
 * SAME pre-week ranking; everyone else starts on the bench. Nine, not seven -
 * see the slot-count guard.
 */
function initialLineup({ roster, rosterSlots = DEFAULT_ROSTER_SLOTS, benchSlots = BENCH_SLOTS, label = 'lineup' }) {
  const slotsByKey = new Map(rosterSlots.map((s) => [s.key, s]));
  const expectedStarters = startingSlotCount(rosterSlots);
  if (INITIAL_FILL_ORDER.length !== expectedStarters) {
    throw new Error(
      `${label}: the fill order has ${INITIAL_FILL_ORDER.length} entries but the roster has ` +
      `${expectedStarters} starting slots (the SUM of slot.count, not the number of slot kinds)`
    );
  }
  // The roster arrives in DRAFT order (round by round), not in rank order, so
  // it is re-sorted here into the same total order `rankCandidates` produces:
  // score, then position rank, then name rank, then id. That is safe precisely
  // because it is the SAME comparator - the initial lineup is defined as "the
  // highest-ranked eligible player for each slot" (prereg 5.1), and ranking is
  // the only ordering this module has. The id tiebreak is included so the two
  // agree exactly; without it, two players tied through name rank would order
  // differently here than on the draft board.
  const available = [...roster].sort((a, b) => b.score - a.score
    || a.positionRank - b.positionRank
    || (a.nameRank ?? Number.MAX_SAFE_INTEGER) - (b.nameRank ?? Number.MAX_SAFE_INTEGER)
    || (String(a.playerId ?? a.teamKey) < String(b.playerId ?? b.teamKey) ? -1
      : String(a.playerId ?? a.teamKey) > String(b.playerId ?? b.teamKey) ? 1 : 0));

  const assigned = new Set();
  const starters = [];
  for (const slotKey of INITIAL_FILL_ORDER) {
    const slot = slotsByKey.get(slotKey);
    if (!slot) throw new Error(`${label}: the fill order names slot ${slotKey}, which the roster shape lacks`);
    const pick = available.find((c) => !assigned.has(c) && slot.eligiblePositions.includes(c.position));
    if (!pick) {
      throw new Error(
        `${label}: no eligible unassigned player for slot ${slotKey}. Rosters are legal by ` +
        'construction, so this means the caps and the roster shape have drifted apart.'
      );
    }
    assigned.add(pick);
    starters.push({ slot: slotKey, ...pick });
  }
  const bench = available.filter((c) => !assigned.has(c));
  if (bench.length !== benchSlots) {
    throw new Error(`${label}: ${bench.length} players on the bench, expected ${benchSlots}`);
  }
  return { starters, bench };
}

// ---------------------------------------------------------------------------
// The frozen artifact
// ---------------------------------------------------------------------------

/**
 * Build every roster for one season-week: 10 teams x 5 replicates = 50.
 *
 * The result is the artifact committed in freeze Commit A. `freezeHash` over it
 * is what the manifest pins, so a regenerated artifact that differs by one pick
 * is detectable rather than merely different.
 */
function buildRosterWeek({
  season, week, candidates, positionRank, nameRankById,
  quotas = CANDIDATE_QUOTAS, replicates = REPLICATES, label = 'rosters',
}) {
  const ranked = rankCandidates({ candidates, positionRank, nameRankById, label });
  const pool = selectCandidatePool({ ranked, quotas, label });
  const rosters = [];
  for (let replicate = 0; replicate < replicates; replicate++) {
    const teams = snakeDraft({ pool, season, week, replicate, label });
    for (const team of teams) {
      const lineup = initialLineup({ roster: team.picks, label });
      rosters.push({
        season: Number(season),
        week: Number(week),
        replicate,
        teamIndex: team.teamIndex,
        draftSlot: team.draftSlot,
        players: team.picks.map(identify),
        starters: lineup.starters.map((s) => ({ slot: s.slot, ...identify(s) })),
        bench: lineup.bench.map(identify),
      });
    }
  }
  if (rosters.length !== TEAM_COUNT * replicates) {
    throw new Error(`${label}: built ${rosters.length} rosters, expected ${TEAM_COUNT * replicates}`);
  }
  return { season: Number(season), week: Number(week), poolSize: pool.length, rosters };
}

/** Pure: the identity fields an artifact records for a drafted player. */
function identify(candidate) {
  return {
    playerId: candidate.playerId ?? null,
    teamKey: candidate.teamKey ?? null,
    position: candidate.position,
    isDefense: !!candidate.isDefense,
  };
}

/**
 * Pure: the freeze hash of a roster artifact.
 *
 * Over the CANONICAL serialization, so key order and formatting cannot move it,
 * and over the identities rather than the scores - a roster is the set of
 * players it drafted, and a scoring-profile change that leaves every pick
 * identical should not read as a different roster set.
 */
function freezeHash(artifact) {
  return crypto.createHash('sha256')
    .update(canonicalJson({
      season: artifact.season,
      week: artifact.week,
      rosters: artifact.rosters.map((r) => ({
        replicate: r.replicate,
        teamIndex: r.teamIndex,
        draftSlot: r.draftSlot,
        players: r.players,
        starters: r.starters,
        bench: r.bench,
      })),
    }), 'utf8')
    .digest('hex');
}

module.exports = {
  ROSTER_SEED,
  CANDIDATE_QUOTAS,
  POOL_SIZE,
  TEAM_COUNT,
  ROUNDS,
  REPLICATES,
  PER_TEAM_CAPS,
  BENCH_SLOTS,
  IR_SLOTS,
  RECENCY_HALF_LIFE_WEEKS,
  HISTORY_SEASONS,
  DEFAULT_ROSTER_SLOTS,
  INITIAL_FILL_ORDER,
  startingSlotCount,
  rosterSize,
  seedFor,
  makeRng,
  seededPermutation,
  weeksAgo,
  recencyWeightedScore,
  rankCandidates,
  selectCandidatePool,
  snakeDraft,
  initialLineup,
  buildRosterWeek,
  freezeHash,
};
